name: my_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.2.0
  rive: ^0.12.4
  universal_io: ^2.2.2
  url_launcher: ^6.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/anim/
