name: my_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.13.0
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  rive: ^0.12.3
  universal_io: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/anim/
